# example-node1-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-sno
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sno2"
  namespace: "sno2"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  baseDomain: "cotton.blue"
  # automatedCleaningMode: metadata
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "4.13.5"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDaqy7YhU9yx28InBRttTWDrsAMqn1txv4Z7ObxrK5ywlILf8LZdWMf8AehwMcxYrkwfC5G48dej6lKXkopQwmu7HCvTtVeU8gn07J6kSl3riAGsbX1wbuCiCjxIXUtHDZUCqc/ZUF/b6efGW0xcmc3fg3xgSWz3YYsH4zWxv211ISfavOjHTHQuVr7ibzEGJrz5S4xJJAY8v9XaYkxbUcaMm2IUFQG7S3RRMywMCSvyhUlPM6/btIVKXfiPy3+nnXhtll2zM3OIVSLOwGQDYhwRxP9TX3vyxidekmxk2gor1aL8S364nNipZITXx5hMHRWrtAX+bgb3FHDdRn9BEYOPLvPVNPKfFZiNULp9ar9QrV1wcfWYGuJ9QSkwfDuRkWVD3KgoZpLEsujP6eAGacyh8jhcv/M5SY5L/sPiX8fklBNWLSuPpMhZAAM1LeKz8iV/GK3jDdVA7nhG7MTRAB0RHnRljDkGcfiEbB+9VmAf+NrfmorPYDL/24o8n1R7tk= mabe@utility.mabe.com"
  clusters:
  - clusterName: "sno2"
    networkType: "OVNKubernetes"
    extraManifestPath: extra-manifests
    clusterLabels:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples
      du-profile: ""
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples in ../policygentemplates:
      # ../policygentemplates/common-ranGen.yaml will apply to all clusters with 'common: true'
      common: true
      # ../policygentemplates/group-du-sno-ranGen.yaml will apply to all clusters with 'group-du-sno: ""'
      group-du-sno: ""
      # ../policygentemplates/example-sno-site.yaml will apply to all clusters with 'sites: "example-sno"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
      sites : "sno2"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.1.0/24
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
      - clock.redhat.com
    ignitionConfigOverride: '{"ignition":{"version":"3.2.0"},"passwd":{"users":[{"name":"core","passwordHash":"$6$AMb00Izb98UzzDII$nTsI8Q3264XOFa.D15WDajrM.4P1LtWLsH2eYYGbnQvl8jswtzfyYsv46WfzSJnAeZ4j1swrBhlYitPQSYlV01"}]}}'
    #additionalNTPSources:
    #  - 1111:2222:3333:4444::2
    # Optionally; This can be used to override the KlusterletAddonConfig that is creted for this cluster:
    crTemplates:
      KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "sno2.cotton.blue"
        role: "master"
        # bmcAddress: idrac-virtualmedia+https://192.168.1.63/redfish/v1/Systems/System.Embedded.1
        bmcAddress: "redfish-virtualmedia://fakefish-192-168-1-62-fakefish.apps.hub.cotton.blue/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "sno-bmc-secret"
        bootMACAddress: "C8:1F:66:D0:99:F0"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: "/dev/sda"
          # byPath: "pci-0000:03:00.0-scsi-0:2:0:0"
        nodeNetwork:
          interfaces:
            - name: "ens1s0"
              macAddress: "C8:1F:66:D0:99:F0"
            - name: "enp5s0f0"
              macAddress: "08:c0:eb:d2:c2:7e"
            - name: "enp5s0f1"
              macAddress: "08:c0:eb:d2:c2:7f"
          config:
            interfaces:
              - name: ens1s0
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  dhcp: false
                  address:
                  - ip: 192.168.1.171
                    prefix-length: 24
              - name: enp5s0f0
                type: ethernet
                state: down
                ipv4:
                  enabled: false
                  dhcp: false
              - name: enp5s0f1
                type: ethernet
                state: down
                ipv4:
                  enabled: false
                  dhcp: false
            dns-resolver:
               config:
                 search:
                 - cotton.blue
                 server:
                 - 192.168.1.1
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: ens1s0
                next-hop-address: 192.168.1.1
                table-id: 254
        # diskPartition:
        # - device: /dev/vdb
        #   pratitions:
        #   - mount_point: /var/recovery
        #     size: 51200
        #     start: 800000        