---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-lab
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterJoined
  clusterSelector:
    matchExpressions:
      - key: sites
        operator: In
        values:
          - "sno1"
          - "sno2"