apiVersion: v1
data:
  quay.lab.example.com..8443: |
    -----BEGIN CERTIFICATE-----
    MIIDWTCCAkGgAwIBAgIUUxBboGY3M+zgbaAYlyJ3mAQsvLswDQYJKoZIhvcNAQEL
    BQAwbTELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
    azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xHDAaBgNVBAMME3F1
    YXkuYWxmbGFiLmF0dC5jb20wHhcNMjIwODE3MjIzODEwWhcNMjMwODA4MjIzODEw
    WjAaMRgwFgYDVQQDDA9xdWF5LWVudGVycHJpc2UwggEiMA0GCSqGSIb3DQEBAQUA
    A4IBDwAwggEKAoIBAQDIsati7WmSa2zSHiMD82zGAH0slaEIM34gvfu2h7894xI7
    xZYK7LPovbXfWEuHHBhP3KXvWjWCiZB4Z5lxYxh/ZUO/yoMiTjnknEjzvrgyUxOV
    0Jl4OW3ZLbX/T7MGJ9Ds+2fbbJtfUVlzSSYCw5g6RYkq8noUWuMl4fO5++so18MD
    MnMDqix7/1RG8GNo5FVHAPyV/Y9vhk3RPGRnjQujTsAphq672LjxakPKvLZTdx4P
    TvUxNI5fiElJ9lk/Ef2zuiAv+mqNpvtjA6g/NXcsVKB7iri9uLL9jd3XV9w/ExnQ
    sg2DHXlN1JjUQ14SwBcVZadGWYsssyvpPZF1QBCFAgMBAAGjRDBCMAsGA1UdDwQE
    AwIC5DATBgNVHSUEDDAKBggrBgEFBQcDATAeBgNVHREEFzAVghNxdWF5LmFsZmxh
    Yi5hdHQuY29tMA0GCSqGSIb3DQEBCwUAA4IBAQC0VUUfXcOK0ZYozSFK+Fyi2uMa
    7n9z1y9o0eIxiRlzMeJ8jQbMZNDYf9VG4LyL8f0TU+qWEu8DLczta/eVOX8WXWWs
    afxeN9AoEuucHstMvwkawWwaIvRqQ4Gxtv+ZMBtHukbrl5HGmwF/Ohg7SpuCQakt
    jt+5ADU0eSqlJuLMT6e5mcvyDaDMD804TjPj+RDOw1ydb2HoOxdy4TRCmfoJYx4x
    6iTY6FNSRI1BzQZCGuFXvjKlfDYIMGqMU+dHcgmQ/VCMKxDrk8lP3WKjNKcLuIcE
    VLecD7oPIbId+g1WDisCMueRgo9GzNosFWzPHqc3KBkakKowppp3O0QBB+ub
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDwDCCAqigAwIBAgIUP/cpzX3+q1w/GxeRQ6vTf8xCRMkwDQYJKoZIhvcNAQEL
    BQAwbTELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
    azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xHDAaBgNVBAMME3F1
    YXkuYWxmbGFiLmF0dC5jb20wHhcNMjIwODE3MjIzODA4WhcNMjUwNjA2MjIzODA4
    WjBtMQswCQYDVQQGEwJVUzELMAkGA1UECAwCVkExETAPBgNVBAcMCE5ldyBZb3Jr
    MQ0wCwYDVQQKDARRdWF5MREwDwYDVQQLDAhEaXZpc2lvbjEcMBoGA1UEAwwTcXVh
    eS5hbGZsYWIuYXR0LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
    AMTgZDfyArZ1NicXOCokuuob635ChiHgSPTyqZ9+DGZHI+eBi7BxyFtV6PwIdOFS
    txS6e8ocZQldQLyxy066dViznKYXT3ZqdZ6ZvnlhWgzphDNDYvCarQ7FI9ParRh8
    b0dEwu9+OICtv6x6uXnqI94TW4DDHG7F5aLhbZzM8DFWVOgl+410ZAO9k251MWU1
    vNe8IriKbunJnOcYBUeGvZqaXsGmHuu/6PoG0MoKgQCHOfSFRzx1605XaohfP7Nq
    mR0ocViOcn4tH5nAVLq/1tRBQO7UykaTHAlZfzLvbmgmeorQoWRouNksnxeQtmJx
    fxDeo/yxyU31UCiP6OYzH6sCAwEAAaNYMFYwCwYDVR0PBAQDAgLkMBMGA1UdJQQM
    MAoGCCsGAQUFBwMBMB4GA1UdEQQXMBWCE3F1YXkuYWxmbGFiLmF0dC5jb20wEgYD
    VR0TAQH/BAgwBgEB/wIBATANBgkqhkiG9w0BAQsFAAOCAQEALutnr7fW8VcYuYU/
    6Y6hpyqpnWg5qS3In/C4l6nyiWneKw7hx6nmTl5AhE8aTVObi3V2IfqWhUMIO7tS
    iHY4yak1jsHp/eE2poOuLNZtsjCouQTRjbbl3GqMOcM1SRv7+sQZaPlfAvosmJXr
    UovLm0OvCp7ORVZmFgkP1jfPPyJZakhWeqB5wKbi9sr3gVjIjiAtcX2W7cxWoTL7
    tPolL7iOxtBsBdY1/sBorqYFrDh0Os9FWx3SWK9yIjWur0QJKwBTBOGP4vtSIgcy
    FkRXaQViBw73gmR3B5wAtWvXBOe4ZqzwP0KP9nWlym6YQy/5jdcb/r/TB5iV3FHv
    dNYtZQ==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: registry-cas
  namespace: openshift-config
