apiVersion: action.open-cluster-management.io/v1beta1
kind: ManagedClusterAction
metadata:
  name: mca-backup-workload
spec:
  actionType: Create
  kube:
    resource: backups.velero.io
    name: backup
    template:
        apiVersion: velero.io/v1
        kind: Backup
        metadata:
          labels:
            velero.io/storage-location: example-dpa-1
          name: backup
          namespace: openshift-adp
        spec:
          defaultVolumesToRestic: false
          hooks: {}
          includedNamespaces:
          - workload
          metadata: {}
          storageLocation: example-dpa-1