apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sno1
generators:
- siteconfig.yaml
resources:
- pull-secret.yaml
- bmc-secret.yaml
- request_cm.yaml
# - job-monitor-cluster-upgrade.yaml