apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeTEuY290dG9uLmJsdWU6ODQ0MyI6eyJhdXRoIjoiYVc1cGREcGphR0Z1WjJWdFpRPT0iLCJlbWFpbCI6Im1hYmVAcmVkaGF0LmNvbSJ9fX0K
kind: Secret
metadata:
  creationTimestamp: null
  name: assisted-deployment-pull-secret
type: kubernetes.io/dockerconfigjson