# example-node1-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-sno
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sno1"
  namespace: "sno1"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  baseDomain: "cotton.blue"
  automatedCleaningMode: metadata
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "4.13.8"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDaqy7YhU9yx28InBRttTWDrsAMqn1txv4Z7ObxrK5ywlILf8LZdWMf8AehwMcxYrkwfC5G48dej6lKXkopQwmu7HCvTtVeU8gn07J6kSl3riAGsbX1wbuCiCjxIXUtHDZUCqc/ZUF/b6efGW0xcmc3fg3xgSWz3YYsH4zWxv211ISfavOjHTHQuVr7ibzEGJrz5S4xJJAY8v9XaYkxbUcaMm2IUFQG7S3RRMywMCSvyhUlPM6/btIVKXfiPy3+nnXhtll2zM3OIVSLOwGQDYhwRxP9TX3vyxidekmxk2gor1aL8S364nNipZITXx5hMHRWrtAX+bgb3FHDdRn9BEYOPLvPVNPKfFZiNULp9ar9QrV1wcfWYGuJ9QSkwfDuRkWVD3KgoZpLEsujP6eAGacyh8jhcv/M5SY5L/sPiX8fklBNWLSuPpMhZAAM1LeKz8iV/GK3jDdVA7nhG7MTRAB0RHnRljDkGcfiEbB+9VmAf+NrfmorPYDL/24o8n1R7tk= mabe@utility.mabe.com"
  clusters:
  - clusterName: "sno1"
    networkType: "OVNKubernetes"
    # extraManifestPath: extra-manifests
    clusterLabels:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples
      du-profile: ""
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples in ../policygentemplates:
      # ../policygentemplates/common-ranGen.yaml will apply to all clusters with 'common: true'
      common: true
      # ../policygentemplates/group-du-sno-ranGen.yaml will apply to all clusters with 'group-du-sno: ""'
      group-du-sno: ""
      # ../policygentemplates/example-sno-site.yaml will apply to all clusters with 'sites: "example-sno"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
      sites : "sno1"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.1.0/24
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
      - clock.redhat.com
    ignitionConfigOverride: '{"ignition":{"version":"3.2.0"},"passwd":{"users":[{"name":"core","passwordHash":"$6$AMb00Izb98UzzDII$nTsI8Q3264XOFa.D15WDajrM.4P1LtWLsH2eYYGbnQvl8jswtzfyYsv46WfzSJnAeZ4j1swrBhlYitPQSYlV01"}]}}'
    #additionalNTPSources:
    #  - 1111:2222:3333:4444::2
    # Optionally; This can be used to override the KlusterletAddonConfig that is creted for this cluster:
    crTemplates:
      KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "sno1.cotton.blue"
        role: "master"
        # bmcAddress: "ilo4-virtualmedia://192.168.1.62/redfish/v1/Systems/1"
        bmcAddress: "redfish-virtualmedia://fakefish-192-168-1-62-fakefish.apps.hub.cotton.blue/redfish/v1/Systems/1"
        # bmcAddress: "ilo4-virtualmedia://fakefish-192-168-1-62-fakefish.apps.hub.cotton.blue/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "sno-bmc-secret"
        bootMACAddress: "98:f2:b3:ed:9e:58"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: /dev/sda
          # deviceName: "/dev/disk/by-path/pci-0000:0a:00.0-scsi-0:1:0:1"
          # serialNumber: 3600508b1001c152315a9ff023826e090
          # serialNumber: S3L1BTL80000N530A26J
        nodeNetwork:
          interfaces:
            - name: "ens1s0"
              macAddress: "98:f2:b3:ed:9e:58"
            - name: "ens1f0np0"
              macAddress: "b8:59:9f:de:72:20"
            - name: "ens1f1np1"
              macAddress: "b8:59:9f:de:72:21"
          config:
            interfaces:
              - name: ens1s0
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  dhcp: false
                  address:
                  - ip: 192.168.1.170
                    prefix-length: 24
              - name: ens1f0np0
                type: ethernet
                state: down
                ipv4:
                  enabled: false
                  dhcp: false
              - name: ens1f1np1
                type: ethernet
                state: down
                ipv4:
                  enabled: false
                  dhcp: false
            dns-resolver:
               config:
                 search:
                 - cotton.blue
                 server:
                 - 192.168.1.1
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: ens1s0
                next-hop-address: 192.168.1.1
                table-id: 254
        # diskPartition:
        # - device: /dev/vdb
        #   pratitions:
        #   - mount_point: /var/recovery
        #     size: 51200
        #     start: 800000        