---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  # The name will be used to generate the placementBinding and placementRule names as {name}-placementBinding and {name}-placementRule
  name: "group-du-sno"
  namespace: "ztp-group"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    group-du-sno: ""
  mcp: "master"
  sourceFiles:
    - fileName: PerformanceProfile.yaml
      policyName: "config-policy"
      spec:
        cpu:
          # These must be tailored for the specific hardware platform
          isolated: 2-6,14-18,26-30,38-42 
          reserved: 0,1,12,13,24,25,36,37
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 32
