---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "sno1"
  namespace: "ztp-site"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    sites: "sno1"
    du-profile: ""
  mcp: "master"
  sourceFiles:
    # - fileName: oadp/namespace.yaml
    #   remediationAction: enforce
    #   policyName: "oadp-policy"
    # - fileName: oadp/subscription.yaml
    #   remediationAction: enforce
    #   policyName: "oadp-policy"
    # - fileName: oadp/secret.yaml
    #   remediationAction: enforce
    #   policyName: "oadp-policy"
    # - fileName: oadp/dataprotectionapp.yaml
    #   remediationAction: enforce
    #   policyName: "oadp-policy"
#Adding lvm
    - fileName: lvm/namespace.yaml
      remediationAction: enforce
      policyName: "odflvm-policy"
    - fileName: lvm/subscription.yaml
      remediationAction: enforce
      policyName: "odflvm-policy"
    - fileName: lvm/instance.yaml
      remediationAction: enforce
      policyName: "odflvm-policy"



      
#  complianceType: musthave
#  remediationAction: enforce  